// Code generated by toolgen; DO NOT EDIT.
package tools

import (
	gen "github.com/chslink/mcp-tools/gen"
	mcp_golang "github.com/metoro-io/mcp-golang"
)

type GetCurrentTimeArguments struct {
	Timezone string `json:"timezone" `
}

var getcurrenttimeTool = gen.Tool{
	Name:        "get_current_time",
	Description: "IANA timezone name (e.g., 'America/New_York', 'Europe/London')",
	Func: func(args GetCurrentTimeArguments) (*mcp_golang.ToolResponse, error) {
		resp, err := ToolGetCurrentTime(args.Timezone)
		return gen.ConvertMcpResp(resp, err)
	},
}

type TestArguments struct {
	SrcTime string `json:"src_time" `
}

var testTool = gen.Tool{
	Name:        "test",
	Description: "xxx",
	Func: func(args TestArguments) (*mcp_golang.ToolResponse, error) {
		resp, err := ToolTest(args.SrcTime)
		return gen.ConvertMcpResp(resp, err)
	},
}

func init() {

	gen.RegisterTool(getcurrenttimeTool)

	gen.RegisterTool(testTool)

}
